@startuml
' Кеширование последних расчетов
MES_API -> Redis: Попытка получения закешированных данных
Redis -> MES_API: Закешированные данные

MES_API -> Redis: Рассчитанный заказ
Redis -> MES_API: Ответ о записи расчетов

Redis -> PostgreSQL: Рассчитанный заказ
@enduml