@startuml
' Кеширование статистических данных
CRM_API -> Redis: Попытка получения данных из кеша
Redis -> CRM_API: Закешированные данные

CRM_API -> Redis: Запись статестических данных
CRM_API -> PostgreSql: Запись статестических данных
@enduml