@startuml
' Кеш часто запрашиваемой информации
Приложение -> Redis: Попытка получения данных из кеша
Redis -> Приложение: Закешированные данные

Приложение -> Redis: Запись рассчитанных данных
Приложение -> PostgreSql: Запись рассчитанных данных
@enduml