@startuml
' Кеширование заказов
Приложение -> Redis: Попытка получения заказа из кеша
Redis -> Приложение: Закешированный заказ

Приложение -> Redis: Заказ
Redis -> Приложение: Ответ о записи заказа

Redis -> PostgreSql: Заказ
@enduml