@startuml
' Кеширование сессий
Приложение -> Redis: Попытка получения сессии из кеша
Redis -> Приложение: Закешированные данные

Приложение -> Redis: Сессия
Redis -> Приложение: Ответ о создании сессии

Redis -> PostgreSql: Сессия
@enduml